channels:
    - defaults
    - conda-forge
dependencies:
    - pvlib=0.9.3
    - cartopy=0.18.0
    - pandoc=2.19.2
    - pip:
        - watermark==2.3.1
        - haversine==2.7.0
        - h5pyd==0.11.0
        - sphinx==5.1.1
        - nbsphinx==0.8.9
        - pydata-sphinx-theme==0.10.1

