channels:
    - defaults
    - conda-forge
dependencies:
    - cartopy=0.18.0
    - pip:
        - folium==0.12.1.post1
        - h5pyd==0.11.0
        - haversine==2.7.0
        - pvlib==0.9.3
        - watermark==2.3.1
