channels:
    - defaults
    - conda-forge
dependencies:
    - cartopy=0.18.0
    - pip:
        - h5pyd==0.11.0
        - haversine==2.7.0
        - matplotlib==3.5.2
        - numpy==1.22.3
        - pandas==1.5.0
        - pvlib==0.9.3
        - scipy==1.7.3
        - watermark==2.3.1
